const GET_SELECTED_BOOK = "GET_SELECTED_BOOK";
const GET_SELECTED_BOOK_SUCCESS = "GET_SELECTED_BOOK_SUCCESS";
const GET_SELECTED_BOOK_FAILURE = "GET_SELECTED_BOOK_FAILURE";

const actions = {
  GET_SELECTED_BOOK,
  GET_SELECTED_BOOK_FAILURE,
  GET_SELECTED_BOOK_SUCCESS
};

export default actions;
